### DISCUSSION TITLE
Ollama giving cURL error 7

### DISCUSSION THREAD

**Discussion by akulmehta** [prism-php/prism#327] [Q&A] [answered]
I have a docker container setup which is running Ollama and Open Web UI. The Ollama and Open Web UI are in the same docker network and Ollama works with Open Web UI. Here is the docker-compose.yml file for this:

```yml
services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    pull_policy: always
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    tty: true
    environment:
      - OLLAMA_FORCE_CPU=1
      - OLLAMA_NUM_THREADS=4
      - OLLAMA_DEBUG=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_MAX_LOADED_MODELS_PER_USER=1
      
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    pull_policy: always
    ports:
      - "3000:8080"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - HOST=0.0.0.0
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  ollama:
  open-webui:

```

Since the Ollama instance port is exposed at 11434, in my terminal the command `curl http://localhost:11434/api/version` shows the version number.

When I am trying to connect my Laravel App which is using Prism (and is running on a separate docker network) to this Ollama instance, I keep getting an error of:

```
Sending to model (gemma3:4b) failed: cURL error 7: Failed to connect to localhost port 11434 after 0 ms: Could not connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:11434/v1/api/chat
```

I have tried several `OLLAMA_URL` env settings for my laravel app also like:

```
OLLAMA_URL="http://localhost:11434"
OLLAMA_URL="http://localhost:11434/v1"
OLLAMA_URL="http://ollama:11434"
OLLAMA_URL="http://ollama:11434/v1"
OLLAMA_URL="http://ollama:11434/api/v1"
```

Is there something special I need to do?
